### ISSUE TITLE
Al generar la tabla no respeta el orden de las variables

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/datos-ext#4]
Tiene que respetar el campo orden. 

Para mayor precisión el orden debería ser: 

primero las null que son pk ordenadas por número de pk, luego las que tienen número de orden y al final las que tienen null tanto en pk como en número de orden. Para desempatar se debe usar el nombre de la variable

**Comment by euginio** [comment]
hecho en el fetch_all de la clase Variable (variable.ts) de repo operativo
